#!/bin/bash
#SBATCH -p gpu -n 2 --gres=gpu:2 -c1 --hint=nomultithread -t 2-00:00
#  (Note: use one MPI process per gpu, update both gres and -n together; max 6)
export PYTHONPATH=/home/mchandra/gitansh/test_electric_fields_2; time mpirun python main.py > output.txt
